#https://hub.docker.com/r/jboss/keycloak/
#https://github.com/keycloak/keycloak-containers/blob/master/docker-compose-examples/keycloak-postgres.yml
version: '3'
volumes:
   postgres_data:
      driver: local
services:
   nginx:
      image: nginx
      container_name: nginx
      restart: on-failure
      volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /etc/nginx/log:/var/log/nginx
      ports:
      - 80:80
      - 443:443
   postgres:
      image: postgres
      networks:
      - default
      restart: always
      container_name: postgres
      volumes:
      - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      ports:
      - 5432:5432
      depends_on:
      - nginx
   keycloak:
      image: mihaibob/keycloak:14.0.0
      environment:
         DB_VENDOR: POSTGRES
         DB_ADDR: postgres
         DB_DATABASE: ${POSTGRES_DB}
         DB_SCHEMA: public
         DB_USER: ${POSTGRES_USER}
         DB_PASSWORD: ${POSTGRES_PASSWORD}
         JDBC_PARAMS: serverTimezone=UTC
      command: -b 0.0.0.0 -Djboss.http.port=8080 -Djboss.https.port=8443
      depends_on:
      - nginx
      - postgres
      ports:
      - 8080:8080
      - 8443:8443
      privileged: true
   quarkus-api:
      image: quarkus/api-fast-jar:latest
      container_name: quarkus-api
      environment:
         POSTGRES_HOST: postgres 
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_PORT: 5432
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         JAVA_ENABLE_DEBUG: "false"
         #QUARKUS_PROFILE: prod
         #QUARKUS_HTTP_SSL_PORT: 8444 
         #QUARKUS_HTTP_SSL_CERTIFICATE_FILE: /etc/quarkus/ssl/web-maker.fr_ssl_certificate.cer
         #QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILE: /etc/quarkus/ssl/_.web-maker.fr_private_key.key
         #QUARKUS_HTTP_INSECURE_REQUESTS: redirect
      command: -Dquarkus.log.level=INFO -Dquarkus.http.cors=false
      #volumes:
      #- /home/root/rest-api/ssl:/etc/quarkus/ssl
      ports:
      - 8081:8081
      depends_on:
      - nginx
      - postgres
      - keycloak
      networks:
      - default
networks:
  default:
    driver: bridge