#https://hub.docker.com/r/jboss/keycloak/
#https://github.com/keycloak/keycloak-containers/blob/master/docker-compose-examples/keycloak-postgres.yml
version: '3'
volumes:
   postgres_data:
      driver: local
services:
   apache:
      image: httpd:latest
      container_name: apache
      ports:
      - 9080:80
      - 9443:443
      volumes:
      - /home/pi/workspace/www:/usr/local/apache2/htdocs/
   postgres:
      image: postgres
      restart: always
      container_name: postgres-dev
      volumes:
      - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      ports:
      - 5435:5432
   nginx:
      image: nginx
      container_name: nginx
      restart: on-failure
#Dockerfile: "Dockerfile"
      volumes:
      - /home/pi/workspace/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/pi/workspace/nginx/certs:/etc/nginx/certs
      - /home/pi/workspace/nginx/log:/var/log/nginx
      ports:
      - 80:80
      - 443:443
   keycloak:
      image: mihaibob/keycloak:14.0.0
      environment:
         DB_VENDOR: POSTGRES
         DB_ADDR: postgres
         DB_DATABASE: ${POSTGRES_DB}
         DB_SCHEMA: public
         DB_USER: ${POSTGRES_USER}
         DB_PASSWORD: ${POSTGRES_PASSWORD}
#KEYCLOAK_USER: webmaker
         JDBC_PARAMS: serverTimezone=UTC
      command: -b 0.0.0.0 -Djboss.http.port=8080 -Djboss.https.port=8443
#KEYCLOAK_PASSWORD: C0rn2par0l
      depends_on:
      - postgres
      ports:
      - 8080:8080
      - 8443:8443
      privileged: true