version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
## CERBOT :  https://blog.eleven-labs.com/fr/https-part-2/
  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/nginx/certs:/etc/nginx/certs"
      - "/var/log/nginx:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
## keycloak : https://hub.docker.com/r/jboss/keycloak/
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_SCHEMA: public
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      command:
        -b 0.0.0.0 -Djboss.http.port=8080 -Djboss.https.port=8443
      ports:
        - "8080:8080"
        - "8443:8443"
      depends_on:
        - postgres

