#https://hub.docker.com/r/jboss/keycloak/
#https://github.com/keycloak/keycloak-containers/blob/master/docker-compose-examples/keycloak-postgres.yml
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      container_name: postgres-dev
      volumes:
        - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: multicommerces
        POSTGRES_USER: postgres_user
        POSTGRES_PASSWORD: postgres_pwd
      ports:  
        - "5435:5432"
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: multicommerces
        DB_SCHEMA: public
        DB_USER: postgres_user
        DB_PASSWORD: postgres_pwd
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        #JDBC_PARAMS: "ssl=true"
      command:
        -b 0.0.0.0 -Djboss.http.port=8080 -Djboss.https.port=8443
      ports:
        - "8080:8080"
        - "8443:8443"
      depends_on:
        - postgres
